import type {
  IngredientCategory,
  IngredientOriginType,
  IngredientStockStatus,
  TriStateFlag,
} from '@atelier/domain'

export const DEMO_INGREDIENTS: Array<{
  inci: string
  tradeName?: string
  category: IngredientCategory
  stockStatus: IngredientStockStatus
  animalDerived: TriStateFlag
  originType: IngredientOriginType
  organicCertified: TriStateFlag
  pricePerKg?: number
  onHandGrams?: number
  notes?: string
}> = [
  {
    inci: 'Aqua',
    category: 'solvent',
    stockStatus: 'in_house',
    animalDerived: 'no',
    originType: 'natural',
    organicCertified: 'unknown',
    onHandGrams: 2000,
  },
  {
    inci: 'Glycerin',
    category: 'solvent',
    stockStatus: 'in_house',
    animalDerived: 'no',
    originType: 'natural',
    organicCertified: 'unknown',
    pricePerKg: 8,
    onHandGrams: 800,
  },
  {
    inci: 'Squalane',
    tradeName: 'Olive squalane',
    category: 'emollient',
    stockStatus: 'in_house',
    animalDerived: 'no',
    originType: 'natural',
    organicCertified: 'unknown',
    pricePerKg: 72,
    onHandGrams: 250,
  },
  {
    inci: 'Caprylic/Capric Triglyceride',
    tradeName: 'MCT oil',
    category: 'carrier',
    stockStatus: 'in_house',
    animalDerived: 'no',
    originType: 'natural',
    organicCertified: 'no',
    pricePerKg: 14,
    onHandGrams: 1000,
  },
  {
    inci: 'Cetearyl Alcohol',
    category: 'emollient',
    stockStatus: 'in_house',
    animalDerived: 'no',
    originType: 'unknown',
    organicCertified: 'unknown',
    pricePerKg: 11,
    onHandGrams: 400,
  },
  {
    inci: 'Shea Butter',
    category: 'emollient',
    stockStatus: 'low',
    animalDerived: 'no',
    originType: 'natural',
    organicCertified: 'unknown',
    notes: 'Last tub is almost empty.',
    pricePerKg: 16,
    onHandGrams: 80,
  },
  {
    inci: 'Beeswax',
    category: 'emollient',
    stockStatus: 'in_house',
    animalDerived: 'yes',
    originType: 'natural',
    organicCertified: 'unknown',
    notes: 'Animal-derived. Blocks vegan products.',
    pricePerKg: 22,
    onHandGrams: 200,
  },
  {
    inci: 'Phenoxyethanol',
    category: 'preservative',
    stockStatus: 'in_house',
    animalDerived: 'no',
    originType: 'synthetic',
    organicCertified: 'no',
    pricePerKg: 18,
    onHandGrams: 150,
  },
  {
    inci: 'Tocopherol',
    category: 'antioxidant',
    stockStatus: 'in_house',
    animalDerived: 'no',
    originType: 'natural',
    organicCertified: 'unknown',
    pricePerKg: 85,
    onHandGrams: 50,
  },
  {
    inci: 'Fragrance',
    tradeName: 'Parfum compound',
    category: 'fragrance',
    stockStatus: 'in_house',
    animalDerived: 'unknown',
    originType: 'synthetic',
    organicCertified: 'no',
    pricePerKg: 48,
    onHandGrams: 100,
  },
  {
    inci: 'Linalool',
    category: 'fragrance',
    stockStatus: 'in_house',
    animalDerived: 'no',
    originType: 'unknown',
    organicCertified: 'unknown',
    pricePerKg: 28,
    onHandGrams: 30,
  },
  {
    inci: 'Coumarin',
    category: 'fragrance',
    stockStatus: 'low',
    animalDerived: 'no',
    originType: 'synthetic',
    organicCertified: 'no',
    pricePerKg: 32,
    onHandGrams: 15,
  },
  {
    inci: 'Butylphenyl Methylpropional',
    tradeName: 'Lilial',
    category: 'fragrance',
    stockStatus: 'in_house',
    animalDerived: 'no',
    originType: 'synthetic',
    organicCertified: 'no',
    notes: 'Check EU ban before using.',
    pricePerKg: 40,
    onHandGrams: 20,
  },
  {
    inci: 'Vanilla Absolute',
    category: 'fragrance',
    stockStatus: 'to_buy',
    animalDerived: 'no',
    originType: 'natural',
    organicCertified: 'unknown',
    notes: 'Wanted for a warmer variant.',
    pricePerKg: 980,
    onHandGrams: 0,
  },
]
