import type { IngredientRule } from '../types.ts'

export const RULES_VERSION = '2026-01-seed'

export const SEED_RULES: IngredientRule[] = [
  {
    id: 'eu-annex-ii-lilial',
    version: RULES_VERSION,
    market: 'EU',
    instrument: 'EU Annex II',
    substance: 'Butylphenyl Methylpropional',
    inciNames: ['Butylphenyl Methylpropional', 'Lilial'],
    effect: 'cannot_sell',
    citationUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32009R1223',
    message: 'Banned in EU cosmetics (Annex II). Remove from formula for EU placement.',
  },
  {
    id: 'eu-annex-v-phenoxyethanol',
    version: RULES_VERSION,
    market: 'EU',
    instrument: 'EU Annex V',
    substance: 'Phenoxyethanol',
    inciNames: ['Phenoxyethanol'],
    maxPercent: 1,
    effect: 'reduce_percent',
    citationUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32009R1223',
    message: 'Phenoxyethanol is limited to 1.0% w/w in leave-on and rinse-off products (Annex V).',
  },
  {
    id: 'eu-allergen-linalool-leave-on',
    version: RULES_VERSION,
    market: 'EU',
    instrument: 'EU Annex III / Allergen labelling',
    substance: 'Linalool',
    inciNames: ['Linalool'],
    labelThresholdPercent: 0.001,
    effect: 'relabel',
    leaveOnOnly: true,
    citationUrl: 'https://ec.europa.eu/growth/sectors/cosmetics/cosing_en',
    message: 'Linalool at or above 0.001% in leave-on products requires allergen labelling on the INCI list.',
  },
  {
    id: 'eu-inci-parfum-wording',
    version: RULES_VERSION,
    market: 'EU',
    instrument: 'EU labelling (1223/2009)',
    substance: 'Fragrance',
    inciNames: ['Fragrance', 'Parfum'],
    effect: 'inci_wording',
    preferredInci: 'Parfum',
    citationUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:3209R1223',
    message: 'EU INCI lists should use "Parfum" rather than "Fragrance".',
  },
  {
    id: 'ifra-cat4-coumarin',
    version: RULES_VERSION,
    market: 'EU',
    instrument: 'IFRA Standard 49th Amendment',
    substance: 'Coumarin',
    inciNames: ['Coumarin'],
    maxPercent: 0.6,
    effect: 'reduce_percent',
    ifraCategory: '4',
    productTypes: ['perfume', 'hybrid'],
    citationUrl: 'https://ifrafragrance.org/standards',
    message: 'Coumarin is limited in IFRA category 4 leave-on fine fragrance.',
  },
  {
    id: 'ifra-cat1-linalool',
    version: RULES_VERSION,
    market: 'EU',
    instrument: 'IFRA Standard 49th Amendment',
    substance: 'Linalool',
    inciNames: ['Linalool'],
    maxPercent: 0.5,
    effect: 'reduce_percent',
    ifraCategory: '1',
    productTypes: ['perfume', 'hybrid'],
    citationUrl: 'https://ifrafragrance.org/standards',
    message: 'Linalool has a lower limit in IFRA category 1 (rinse-off) than category 4.',
  },
  {
    id: 'asean-lilial-restricted',
    version: RULES_VERSION,
    market: 'ASEAN',
    instrument: 'ASEAN Cosmetic Directive Annex II (partial alignment)',
    substance: 'Butylphenyl Methylpropional',
    inciNames: ['Butylphenyl Methylpropional', 'Lilial'],
    maxPercent: 0.1,
    effect: 'reduce_percent',
    citationUrl: 'https://asean.org/our-communities/economic-community/integration-with-global-economy/asean-cosmetic-directive/',
    message: 'ASEAN seed rule: Lilial restricted to 0.1% (not banned). EU and ASEAN chips may differ.',
  },
  {
    id: 'asean-phenoxyethanol',
    version: RULES_VERSION,
    market: 'ASEAN',
    instrument: 'ASEAN Cosmetic Directive Annex VI',
    substance: 'Phenoxyethanol',
    inciNames: ['Phenoxyethanol'],
    maxPercent: 1,
    effect: 'reduce_percent',
    citationUrl: 'https://asean.org/our-communities/economic-community/integration-with-global-economy/asean-cosmetic-directive/',
    message: 'Phenoxyethanol limited to 1.0% w/w in ASEAN seed rules.',
  },
]
